{% set name = "madminer" %}
{% set version = "0.9.6" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/madminer-{{ version }}.tar.gz
  sha256: 17eedd09da79db371530336904f248e8cde00032a53e50bbe36cbbb92f1c0939

build:
  # so use or statements in skip
  # Will fail on Windows as PyTorch doe not support Windows, but failing on
  # a noarch is preferred by the conda-forge maintainers
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  # Python 3.12+ is not allowed as uproot3_methods fails with
  # AttributeError: 'FileFinder' object has no attribute 'find_module'.
  # uproot3 and uproot3-methods are deprecated, so these should be removed
  # in the future.
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<3.12
    - h5py
    - matplotlib-base >=2.0.0
    - particle >=0.16.0
    - scipy >=1.0.0
    - pytorch >=1.0.0
    - uproot3 >=3.14.1
    - vector >=0.8.4
    - sympy >=0.7.4
    - numpy  # compatible versions controlled through scipy

test:
  imports:
    - madminer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/madminer-tool/madminer
  summary: Mining gold from MadGraph to improve limit setting in particle physics.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://madminer.readthedocs.io/
  dev_url: https://github.com/madminer-tool/madminer

extra:
  recipe-maintainers:
    - matthewfeickert
